/**
 * Build script: bundles @medv/finder into an IIFE string for page injection.
 * Run: npx tsx src/agent/scripts/build-finder-inject.ts
 * Output: src/agent/scripts/finder-inject.ts (auto-generated)
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const __dirname = dirname(fileURLToPath(import.meta.url))

async function main() {
  const result = await build({
    stdin: {
      contents: `
        import { finder } from '@medv/finder';
        window.__autoGuideFinder = finder;
      `,
      resolveDir: join(__dirname, '../../..'),
      loader: 'ts',
    },
    bundle: true,
    format: 'iife',
    write: false,
    minify: true,
    target: 'es2020',
  })

  const code = result.outputFiles[0]!.text
  const output = `// Auto-generated by build-finder-inject.ts — do not edit
export const FINDER_INJECT_SCRIPT = ${JSON.stringify(code)};
`
  writeFileSync(join(__dirname, 'finder-inject.ts'), output)
  console.log(`[build] finder-inject.ts written (${code.length} bytes)`)
}

main()
